# Generated by Django 4.2.13 on 2024-06-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='image_par_heure',
            field=models.ImageField(blank=True, default='default_image_par_heure.png', null=True, upload_to='reports/images/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(upload_to='reports/files/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='image',
            field=models.ImageField(blank=True, default='default_image.png', null=True, upload_to='reports/images/'),
        ),
    ]
